---
layout: Resumé
title: Chad Johnson's Resumé
---
# Chad Johnson
Data Science Student | Accounting Professional

<div id="webaddress">
<a href="chadjohnson31901@gmail.com">chadjohnson31901@gmail.com</a>
| <a href="https://www.linkedin.com/in/chad-johnson-2960ba223/">LinkedIn</a>
| <a href="https://github.com/Chadjohnson3">GitHub</a>
</div>

## EDUCATION

### Master of Science in Data Science
_Eastern University_ | Oct 2024 - Present

### Bachelor of Science in Accounting | Minor in Data Science
_Brigham Young University-Idaho_ | Sep 2021 - Jul 2024
- Data Science Society Member
- Student Accounting Society Member

## PROFESSIONAL EXPERIENCE

### Owner, BookVista Bookkeeping
_Remote_ | Oct 2024 - Present
- Manage a small bookkeeping business serving service-based industries including healthcare, real estate, and IT
- Provide monthly bookkeeping, financial reporting, and tax support
- Streamline processes to help clients focus on core operations

### Staff Auditor
_SBNG, P.C_ | Aug 2024 - Oct 2024
- Performed financial and compliance audits, client reviews, and data analysis
- Maintained client relationships
- Ensured AICPA standards
- Provided insights through risk-based approaches

### Audit & Assurance Intern
_Cooper Norman Business Advisors & CPAs_ | Jan 2024 - April 2024
- Engaged in audits, reviews, and compilations of financial statements
- Enhanced software capabilities using Practice CS Professional Suite, QuickBooks Online, and Excel
- Developed audit analytical skills, applied GAAP & GAAS
- Collaborated with team members and clients on complex projects

### Teacher's Assistant
_Brigham Young University-Idaho_ | Aug 2023 - Dec 2023
- Assisted professor for introductory SQL class
- Taught classes in professor's absence
- Prepared and updated course materials
- Graded assignments and provided student support

### Online Pickup & Delivery/Inventory Tracking
_Walmart_ | May 2022 - May 2023
- Performed inventory checks and replenishment
- Ensured product availability
- Fulfilled online orders efficiently
- Trained new employees, contributing to operational efficiency

## SKILLS
- Data Visualization
- Data Wrangling
- Basic Web App Development
- Machine Learning
- Accounting & Finance
- Bookkeeping
- Budgeting
- Forecasting
- Strong Communication
- Leadership

## TECHNICAL SKILLS
- Programming: R, Python, MySQL, HTML, Git, JAVA
- Software: Microsoft Office Suite, Tableau, Power BI

## CERTIFICATIONS
- Structured Query Language, MyEducator
- Complete Guide to Power BI for Data Analysts, Microsoft Press
- Certified Advanced QuickBooks ProAdvisor, Intuit

## VOLUNTEER EXPERIENCE

### Teaching Volunteer
_The Church of Jesus Christ of Latter-day Saints_ | Oct 2024 - Present
- Teach high school students early-morning seminary classes
- Develop communication and leadership skills
- Demonstrate commitment by engaging students before school

### Full-time Volunteer Representative
_The Church of Jesus Christ of Latter-day Saints_ | Aug 2019 - Aug 2021
- Demonstrated leadership in team training and goal achievement
- Managed extensive workweeks up to 100 hours
- Overcame pandemic challenges with creative problem-solving
- Developed skills in meeting leadership and team support


<!-- ### Footer

Last updated: May 2013 -->